window.STORY = {
  qq: {
    groupName: "无畏契约开黑群",
    myName: "铭哥",
    myAvatar: "assets/avatar.png",
    avatars: { "AP":"#5b8def", "汐泊诺思":"#9b6de8", "小满":"#e86d9b", "大熊":"#6d8a9b" },
    messages: [
      {t:"time", text:"2026年7月18日 22:14"},
      {t:"text", who:"me", text:"兄弟们，我要跟你们说个事"},
      {t:"text", who:"me", text:"我好像恋爱了"},
      {t:"text", who:"them", name:"汐泊诺思", text:"？？？"},
      {t:"text", who:"them", name:"汐泊诺思", text:"你电脑里那 30 个 G 终于装不下了是吧"},
      {t:"text", who:"them", name:"AP", text:"你他妈天天在家打游戏，跟谁恋爱，跟你的钻石段位？"},
      {t:"text", who:"me", text:"游戏里认识的"},
      {t:"text", who:"me", text:"认识三个月了，杭州的，声音巨好听"},
      {t:"text", who:"them", name:"汐泊诺思", text:"女生？"},
      {t:"text", who:"me", text:"女生"},
      {t:"text", who:"them", name:"AP", text:"先说是人是鬼"},
      {t:"text", who:"them", name:"小满", text:"网恋啊，铭哥你醒醒"},
      {t:"text", who:"me", text:"她人真的很好，我状态最差那阵子，是她一直陪我"},
      {t:"text", who:"them", name:"大熊", text:"。"},
      {t:"text", who:"them", name:"汐泊诺思", text:"上图！没图说个屁"},
      {t:"text", who:"me", text:"回头给你们看"},
      {t:"time", text:"2026年7月20日 23:41"},
      {t:"text", who:"them", name:"AP", text:"铭哥，我认真的，你去查查什么叫杀猪盘"},
      {t:"text", who:"them", name:"AP", text:"网恋对象，声音好听，从不肯视频，杭州，还自称高中女生"},
      {t:"text", who:"them", name:"AP", text:"要素全齐了，你 BYD 别被骗了"},
      {t:"text", who:"them", name:"汐泊诺思", text:"哈哈哈哈哈哈要素全齐"},
      {t:"text", who:"them", name:"小满", text:"她多大啊？"},
      {t:"text", who:"me", text:"高二，说是下学期高三"},
      {t:"text", who:"them", name:"小满", text:"高中生……那你更得小心，未成年的钱你也敢要？"},
      {t:"text", who:"me", text:"我没花过她钱，是她总想给我花钱"},
      {t:"text", who:"me", text:"我都不好意思"},
      {t:"text", who:"them", name:"AP", text:"？？？"},
      {t:"text", who:"them", name:"AP", text:"这就更不对劲了兄弟，她图你什么？图你钻石？"},
      {t:"text", who:"them", name:"大熊", text:"图他打游戏菜，好带他上分"},
      {t:"text", who:"them", name:"汐泊诺思", text:"大熊你终于说话了"},
      {t:"text", who:"me", text:"滚滚滚"},
      {t:"text", who:"me", text:"反正我信她"},
      {t:"text", who:"them", name:"AP", text:"行，你信。出了事别哭"},
      {t:"time", text:"2026年7月23日 21:33"},
      {t:"text", who:"me", text:"她给我发照片了！"},
      {t:"text", who:"them", name:"汐泊诺思", text:"来了来了，上图上图"},
      {t:"text", who:"me", text:"是她初中的照片，她说她现在变了好多"},
      {t:"text", who:"me", text:"我发群里你们看看"},
      {t:"text", who:"them", name:"AP", text:"等等，初中照片？"},
      {t:"text", who:"them", name:"AP", text:"她为什么不发现在的？"},
      {t:"text", who:"me", text:"她害羞嘛，说见面就知道了"},
      {t:"text", who:"them", name:"小满", text:"铭哥……哪个正常女生见网友发初中照片啊"},
      {t:"text", who:"me", text:"我信她"},
      {t:"text", who:"them", name:"大熊", text:"信字值多少钱"},
      {t:"text", who:"me", text:"值一张高铁票"},
      {t:"text", who:"them", name:"汐泊诺思", text:"你买票了？？？"},
      {t:"text", who:"me", text:"嗯。后天去杭州。她酒店都订好了，我就出个车票钱"},
      {t:"text", who:"them", name:"AP", text:"我操"},
      {t:"text", who:"them", name:"AP", text:"铭哥，你听我说，你冷静，你 TM 冷静"},
      {t:"text", who:"me", text:"我冷静过了。我查过杀猪盘了，她不是"},
      {t:"text", who:"them", name:"AP", text:"你查了？你查了啥？你查了个寂寞"},
      {t:"text", who:"me", text:"骗子不会记得我哪天不开心。她记得"},
      {t:"text", who:"them", name:"小满", text:"……"},
      {t:"text", who:"them", name:"大熊", text:"……"},
      {t:"text", who:"them", name:"AP", text:"行。你非要去。那你给我报备"},
      {t:"text", who:"me", text:"行，我给你报备"},
      {t:"text", who:"them", name:"汐泊诺思", text:"我也要我也要，报备给我一份"},
      {t:"text", who:"me", text:"你俩一人一份"},
      {t:"text", who:"them", name:"小满", text:"平安回来，铭哥"},
      {t:"time", text:"2026年7月24日 22:58"},
      {t:"text", who:"me", text:"明天早上的车"},
      {t:"text", who:"me", text:"兄弟们，等我消息"},
      {t:"text", who:"them", name:"AP", text:"等你报备"},
      {t:"text", who:"them", name:"汐泊诺思", text:"平安！"},
      {t:"text", who:"them", name:"小满", text:"平安！！"},
      {t:"text", who:"them", name:"大熊", text:"平安。"},
      {t:"text", who:"me", text:"走了"},
    ]
  },
  wechat: {
    myName: "LuvisDrug",
    myAvatar: "assets/avatar.png",
    contacts: [
      {id:"tuanzi", name:"帅气鲨团子", av:"🦈", last:"明天见。"},
      {id:"apxs", name:"APXS", av:"A", color:"#5b8def", last:"……如果看到我的号上线，别信。"},
      {id:"xibo", name:"汐泊诺思", av:"汐", color:"#9b6de8", last:"到时候你就知道了！"},
      {id:"mom", name:"妈妈", av:"妈", color:"#e86d9b", last:"注意安全，到了给妈说一声"},
      {id:"cousin", name:"表哥", av:"表", color:"#6d8a9b", last:"行，转你了，800 够不"}
    ],
    chats: {
      tuanzi: [
        {t:"time", text:"2026年1月18日 01:12"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你怎么还没睡"},
        {t:"text", who:"me", text:"睡不着"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"又失眠啦？"},
        {t:"text", who:"me", text:"嗯"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"那你陪我打两把，打到你想睡为止"},
        {t:"text", who:"me", text:"你不困吗"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我不困。我陪你"},
        {t:"text", who:"me", text:"团子"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"嗯？"},
        {t:"text", who:"me", text:"没什么"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"好啦好啦，来，上号，姐姐带你赢"},
        {t:"text", who:"me", text:"你是妹妹"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"姐姐是尊称！来上号！"},
        {t:"time", text:"2026年7月10日 22:47"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"铭铭，我跟你说个事"},
        {t:"text", who:"me", text:"你说"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我下个月要放暑假了"},
        {t:"text", who:"me", text:"嗯！"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我……想见你"},
        {t:"text", who:"me", text:"？？？"},
        {t:"text", who:"me", text:"真的假的"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"真的。我都跟我爸说了"},
        {t:"text", who:"me", text:"你爸同意？？"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"他说我长大了，自己决定"},
        {t:"text", who:"me", text:"那我去找你！我买票！"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你不用管，酒店我来订，你人到就行"},
        {t:"text", who:"me", text:"那怎么行，哪能让你花钱"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你到杭州就是给我面子啦！"},
        {t:"time", text:"2026年7月14日 23:58"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我真的是独生女啦，我爸妈就我一个"},
        {t:"text", who:"me", text:"好好好，独生女独生女"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你不信！"},
        {t:"text", who:"me", text:"我信我信"},
        {t:"time", text:"2026年7月15日 07:12"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我哥送我上学去了，路上好挤"},
        {t:"text", who:"me", text:"你哥？"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我哥啊，我不是说过吗，他在二中读高三，顺路带我"},
        {t:"text", who:"me", text:"……你昨天不是说你独生女吗"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我说过吗？嘻嘻，我记错啦"},
        {t:"text", who:"me", text:"？"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"到学校了，拜拜！"},
        {t:"time", text:"2026年7月17日 22:03"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"明天月考，好紧张，感觉要完蛋了"},
        {t:"text", who:"me", text:"你成绩不是挺好的吗"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"这次不一样，数学好难"},
        {t:"text", who:"me", text:"别怕，考完我陪你打游戏"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"好耶！"},
        {t:"time", text:"2026年7月18日 15:26"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"上班摸鱼被老板骂了呜呜呜"},
        {t:"text", who:"me", text:"？？？"},
        {t:"text", who:"me", text:"上班？"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"啊不是，说错了，是上课！上课！"},
        {t:"text", who:"me", text:"……"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你看我困的，脑子都糊了"},
        {t:"text", who:"me", text:"你今天不是月考吗"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"考完了嘛！"},
        {t:"text", who:"me", text:"行吧"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"别多想啦，我困了先睡了，晚安！"},
        {t:"time", text:"2026年7月19日 00:31"},
        {t:"text", who:"me", text:"团子，开个视频呗"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"不行！！我爸爸会发现的！！"},
        {t:"text", who:"me", text:"就一分钟"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"求你了铭铭，等我见到你，你想看多久看多久"},
        {t:"text", who:"me", text:"……好吧"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"嘻嘻，晚安！"},
        {t:"time", text:"2026年7月20日 23:19"},
        {t:"voice", who:"them", name:"帅气鲨团子", dur:"6", trans:"人家就是想见你嘛"},
        {t:"text", who:"me", text:"你声音今天怎么不太一样"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"刚洗完澡嗓子哑啦"},
        {t:"text", who:"me", text:"哦"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你什么时候来呀，我数着日子呢"},
        {t:"time", text:"2026年7月23日 21:27"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"这是我初中的照片，我现在变了好多"},
        {t:"expired", who:"them", name:"帅气鲨团子"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你看到我就知道了"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"不许嫌我丑！"},
        {t:"text", who:"me", text:"不嫌不嫌！"},
        {t:"text", who:"me", text:"你穿校服真好看"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"嘻嘻，见到真人你就知道了"},
        {t:"time", text:"2026年7月24日 23:05"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我订好啦！杭州西湖区文三路，XX 酒店，你到了直接报我名字就行"},
        {t:"loc", who:"them", name:"帅气鲨团子", src:"assets/p-map.webp", label:"[定位] 杭州市西湖区文三路 515 号附近"},
        {t:"text", who:"me", text:"好！明天见"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"明天见！"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"铭铭，谢谢你愿意来"},
        {t:"text", who:"me", text:"该说谢谢的是我"},
        {t:"time", text:"2026年7月24日 23:58"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"铭铭，你睡了吗"},
        {t:"text", who:"me", text:"没"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我睡不着"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"我有点害怕"},
        {t:"text", who:"me", text:"怕什么？"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"怕你见了我觉得我不好看，就走了"},
        {t:"text", who:"me", text:"不会的"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"你保证？"},
        {t:"text", who:"me", text:"我保证"},
        {t:"text", who:"them", name:"帅气鲨团子", text:"好。那我睡了。明天见"},
        {t:"text", who:"me", text:"明天见。"}
      ],
      apxs: [
        {t:"time", text:"2026年7月24日 02:57"},
        {t:"text", who:"me", text:"我第一次见她吧我震惊了"},
        {t:"text", who:"me", text:"咋这么大"},
        {t:"time", text:"2026年7月24日 10:20"},
        {t:"text", who:"them", name:"APXS", text:"等一下。我突然想起来。你他妈去杭州不去找帅气鲨团子那个小女孩吧？"},
        {t:"text", who:"me", text:"她喊我去的。酒店都是她买的"},
        {t:"text", who:"me", text:"我就出了个车票钱"},
        {t:"text", who:"me", text:"她才170"},
        {t:"text", who:"them", name:"APXS", text:"你BYD别被她骗了"},
        {t:"sticker", who:"them", name:"APXS", src:"assets/sticker-sad.jpg"},
        {t:"text", who:"me", text:"放心兄弟"},
        {t:"text", who:"me", text:"咋可能呢"},
        {t:"text", who:"me", text:"应该不能"},
        {t:"text", who:"me", text:"我给你报备"},
        {t:"text", who:"me", text:"行"},
        {t:"sticker", who:"me", src:"assets/sticker-heart.jpg"},
        {t:"time", text:"2026年7月25日 00:13"},
        {t:"text", who:"me", text:"AP。如果月底我还没回来，就把我电脑寄给你。密码你知道的。"},
        {t:"text", who:"me", text:"……如果看到我的号上线，别信。"}
      ],
      xibo: [
        {t:"time", text:"2026年7月24日 21:06"},
        {t:"text", who:"them", name:"汐泊诺思", text:"打不打"},
        {t:"text", who:"me", text:"不打。"},
        {t:"text", who:"them", name:"汐泊诺思", text:"看见你上号了怎么办"},
        {t:"text", who:"me", text:"我在客厅"},
        {t:"text", who:"me", text:"哎对了，我不是过几天要去杭州"},
        {t:"text", who:"me", text:"我去这小孩胸有点大。"},
        {t:"text", who:"me", text:"我说实话"},
        {t:"text", who:"me", text:"她昨天给我发的还是她初中的照片"},
        {t:"text", who:"me", text:"我一看惊呆了"},
        {t:"text", who:"me", text:"现在得啥样"},
        {t:"expired", who:"me"},
        {t:"text", who:"me", text:"这得是啥罩杯了"},
        {t:"text", who:"them", name:"汐泊诺思", text:"真b啊"},
        {t:"text", who:"them", name:"汐泊诺思", text:"b+吧"},
        {t:"text", who:"them", name:"汐泊诺思", text:"现在肯定是有c了"},
        {t:"text", who:"them", name:"汐泊诺思", text:"😱"},
        {t:"text", who:"them", name:"汐泊诺思", text:"哎哟我去"},
        {t:"text", who:"them", name:"汐泊诺思", text:"受不了了"},
        {t:"text", who:"them", name:"汐泊诺思", text:"😿"},
        {t:"sticker", who:"them", name:"汐泊诺思", src:"assets/sticker-sad2.jpg"},
        {t:"text", who:"them", name:"汐泊诺思", text:"我不得劲"},
        {t:"text", who:"them", name:"汐泊诺思", text:"哎"},
        {t:"text", who:"them", name:"汐泊诺思", text:"自卑了"},
        {t:"text", who:"them", name:"汐泊诺思", text:"😿"},
        {t:"time", text:"2026年7月24日 21:25"},
        {t:"text", who:"them", name:"汐泊诺思", text:"对了，我把那张照片和一段语音打包发你了，存好"},
        {t:"file", who:"them", name:"汐泊诺思", fname:"到时候再看.zip", ficon:"📦"},
        {t:"text", who:"them", name:"汐泊诺思", text:"你忘了为啥去杭州就打开。别谢我，谢你自己还记得"},
        {t:"text", who:"me", text:"？"},
        {t:"text", who:"them", name:"汐泊诺思", text:"到时候你就知道了！"},
        {t:"text", who:"me", text:"神神秘秘的"},
        {t:"text", who:"them", name:"汐泊诺思", text:"走了走了，困了，你也早点睡，明天一路顺风"}
      ],
      mom: [
        {t:"time", text:"2026年7月20日 20:12"},
        {t:"text", who:"them", name:"妈妈", text:"铭泽，吃饭了没"},
        {t:"text", who:"me", text:"吃了妈"},
        {t:"text", who:"them", name:"妈妈", text:"别老打游戏，毕业了该想想工作了"},
        {t:"text", who:"me", text:"知道了知道了"},
        {t:"text", who:"them", name:"妈妈", text:"你爸那边，你别放在心上"},
        {t:"text", who:"me", text:"嗯"},
        {t:"time", text:"2026年7月24日 19:47"},
        {t:"text", who:"them", name:"妈妈", text:"你姨说你买火车票了？你要去哪？"},
        {t:"text", who:"me", text:"去杭州，同学聚会"},
        {t:"text", who:"them", name:"妈妈", text:"几天回来？"},
        {t:"text", who:"me", text:"两三天吧"},
        {t:"text", who:"them", name:"妈妈", text:"注意安全，到了给妈说一声"},
        {t:"text", who:"me", text:"好"}
      ],
      cousin: [
        {t:"time", text:"2026年7月22日 22:31"},
        {t:"text", who:"them", name:"表哥", text:"咋了突然借钱"},
        {t:"text", who:"me", text:"我要去趟杭州"},
        {t:"text", who:"them", name:"表哥", text:"杭州？见网友？"},
        {t:"text", who:"me", text:"嗯"},
        {t:"text", who:"them", name:"表哥", text:"你小心点，网上的人，谁知道对面是人是狗"},
        {t:"text", who:"me", text:"我知道"},
        {t:"text", who:"them", name:"表哥", text:"行，转你了，800 够不"},
        {t:"text", who:"me", text:"够了，谢哥"}
      ]
    },
    moments: [
      { name:"LuvisDrug", av:"assets/avatar.png", time:"7月24日 22:40", text:"去见一个重要的人", img:"assets/p-station.webp", comments:"妈妈评论：去哪啊？", comments2:"（LuvisDrug 未回复）" },
      { name:"汐泊诺思", av:"汐", color:"#9b6de8", time:"7月23日 20:15", text:"减肥第五天，点了个炸鸡，明天重新开始", img:"", comments:"LuvisDrug 评论：哈哈哈哈哈哈", comments2:"汐泊诺思 回复 LuvisDrug：滚" }
    ]
  },  safari: {
    history: [
      {t:"2026-08-26 00:00", title:"杭州市西湖区文三路 · 街景", url:"ditu.com/streetview/wensanlu", fav:"🗺", ghost:true},
      {t:"2026-07-25 00:06", title:"德州到杭州 高铁票 改签", url:"12306.cn/order/revoke", fav:"🚆"},
      {t:"2026-07-24 23:58", title:"杭州 网恋 失联 大学生", url:"baidu.com/s?q=杭州网恋失联", fav:"🔍", deleted:true},
      {t:"2026-07-24 23:52", title:"网恋对象 从不肯视频 是骗子吗", url:"zhihu.com/question/8152", fav:"🔍"},
      {t:"2026-07-24 23:47", title:"杀猪盘 特征", url:"baidu.com/s?q=杀猪盘特征", fav:"🔍"},
      {t:"2026-06-15 02:31", title:"德州 心理咨询 预约", url:"dzdoc.com/psych/appt", fav:"🏥"},
      {t:"2026-06-15 02:20", title:"大学生 挂科 想退学 怎么办", url:"zhihu.com/question/7011", fav:"🔍"}
    ],
    searchPresets: [
      {q:"帅气鲨团子", label:"搜索：帅气鲨团子", results:[
        {t:"战绩页 · 无畏契约（国服）", u:"vanguard.qq.com/profile/12884021", s:"账号：帅气鲨团子 · 段位：钻石 · 最近登录：2026-07-26（之后再无登录记录）"},
        {t:"贴吧回帖（2025-11）", u:"tieba.baidu.com/p/88213", s:"「这个号是挂吗，鲨团子？」 回复：「不是，真大神。」"},
        {t:"搜索结果提示", u:"—", s:"未找到与「帅气鲨团子」相关的真实身份信息：无实名、无学校、无照片。该网名仅存在于游戏与社交平台。"}
      ]},
      {q:"李铭泽", label:"搜索：李铭泽", results:[
        {t:"德州XX大学 · 电竞社团成员名单（2024届）", u:"edu.dzxx.cn/club/esports", s:"李铭泽 · 游戏ID：LMZ·铭 · 位置：决斗者"},
        {t:"失踪人口信息（2026-08-20）", u:"police.gov.cn/missing/0820", s:"李铭泽，男，22岁，山东德州人，7月25日前往杭州后失联，家属已报警。"}
      ]},
      {q:"文三路", label:"搜索：文三路 街景", results:[
        {t:"杭州市西湖区文三路 街景", u:"ditu.com/streetview/wensanlu", s:"打开街景视图…（红圈标出一栋楼，楼下有一个外卖柜和一家关门的店）"}
      ]}
    ]
  },
  notes: [
    {id:"plan", title:"行程规划", date:"7月24日", text:"杭州行程 7.25\nG189 德州东 07:52 → 杭州东 12:41\n酒店：西湖区文三路 XX 酒店（团子订的，报她名字）\n她说在文三路 515 号那栋楼下等我\n16 号出口，别走错\n回来车票先不买，看她安排"},
    {id:"psych", title:"心理科就诊记录", date:"2026年3月12日", text:"德州市XX医院 · 心理科\n就诊人：李铭泽（男，22岁）\n主诉：失眠、情绪低落、注意力下降，有退学念头\n建议：规律作息，适度运动，必要时复诊\n（医生签名字迹潦草）\n\n——这是半年前的事。那时候他没跟任何人说。"},
    {id:"d1", title:"日记 · 7月10日", date:"7月10日", text:"团子说她想见我。她说她一个人太久了。我也是。\n其实我早就想去了，只是怕。怕见面就散了，怕网线那头不是我想的那个人。\n但她说酒店她订，说只要我人到。\n我买了票。"},
    {id:"d2", title:"日记 · 7月15日", date:"7月15日", text:"今天她说话有点怪，一会说独生女一会说有哥哥，还说过一次「上班」。\nAP 说我被冲昏头了。我没反驳。\n可我想起一月份那个晚上，我躺在床上不想活的时候，是她的声音把我拽回来的。\n骗子不会记得我哪天不开心。"},
    {id:"d3", title:"日记 · 7月20日", date:"7月20日", text:"群里都在劝我。AP 说得最狠。\n我搜了杀猪盘。特征我全对得上：网恋、不视频、要钱。\n可她从没跟我要过钱。一分都没有。\n反而是我，总想给她花。她还不让。\n奇怪。"},
    {id:"d4", title:"日记 · 7月24日", date:"7月24日", text:"如果她骗我，我认了。\n但如果她没有——我不能再让她一个人。"},
    {id:"d5", title:"日记 · 7月24日 深夜", date:"7月24日 深夜", text:"我把这个文件夹锁起来了。\n密码是见面的日子，加她的猫。\n如果我回不来，别让任何人打开它。\n包括 AP。他太聪明，会猜到的。"}
  ],
  photos: [
    {src:"assets/p-park.webp", cap:"IMG_0725_1402.jpg · 7/25 14:02 · 西湖·断桥"},
    {src:"assets/p-oldtown.webp", cap:"IMG_0725_1520.jpg · 7/25 15:20 · 灵隐寺山门"},
    {src:"assets/p-skyline.webp", cap:"IMG_0725_1834.jpg · 7/25 18:34 · 文三路街景"},
    {src:"assets/p-museum.webp", cap:"IMG_0725_1902.jpg · 7/25 19:02 · 某栋楼外景（构图仓促，像是在确认位置）", ev:5},
    {src:"assets/p-minghe.webp", cap:"IMG_0725_2311.jpg · 7/25 23:11 · 巷口路灯下（对焦模糊）"},
    {src:"assets/p-station.webp", cap:"IMG_0726_0047.jpg · 7/26 00:47 · 同一栋楼，夜里（只拍了楼顶的灯牌）"}
  ],
  news: [
    {id:"n1", title:"深夜无人操作的电脑自行亮屏？警方：正在调查", src:"杭州都市快讯 · 2026-08-12", ghost:true, body:"近日有市民反映，某网吧凌晨三台电脑自行开机，屏幕上打出「别找我」字样，警方到场后电脑恢复正常，未发现人为操作痕迹。监控画面未拍到异常。\n警方提醒：网络信息请理性看待，不信谣不传谣。"},
    {id:"n2", title:"警惕以「网恋奔现」为诱饵的非法拘禁案件", src:"杭州警方反诈提醒 · 2026-08-15", ev:7, body:"近期多地出现以网络交友、线下见面为诱饵，将受害人诱骗至指定地点后限制人身自由的案件。\n警方提示：网络交友需谨慎，涉及异地见面、不明地址、大额消费，请务必提高警惕，及时报警。\n\n（你看完这条，把鼠标挪开了。它说的每一个字，都像在说铭泽。）"},
    {id:"n3", title:"寻人启事 · 李铭泽，男，22 岁", src:"失踪人口信息 · 2026-08-20", body:"李铭泽，22 岁，山东德州人，德州 XX 大学大四学生。2026 年 7 月 25 日前往杭州后失联，7 月 26 日手机失去信号。家属已报警。\n如有线索请联系德州 / 杭州警方。\n[配图：李铭泽的头像]"}
  ],
  voice: {
    morse: { name:"LOOPmorsecode.wav", meta:"7/26 02:11 · 来自 iCloud 同步 · 来源设备：LuvisDrug 的 iPhone", src:"assets/morse.wav", note:"深夜环境音 + 规律滴答声（循环，约 40 秒）。", decode:"滴答声解码（配合摩斯对照表）：\n「救我」重复 3 遍 + 坐标 N30.283, E120.133\n（≈ 文三路 515 号一带）", ghost:"第 39 秒……好像有人在喊「AP」。倒回去听，没有了。" }
  },
  finder: {
    zip: { name:"到时候再看.zip", icon:"📦" },
    zipFiles: [
      {t:"img", icon:"📷", name:"初中.jpg（已损坏）", desc:"只能看清：一张模糊的、穿校服的少女面孔，五官糊成一片。右下角时间戳 2026-07-23。", ev:1, blur:true, src:"assets/blur-source.webp"},
      {t:"voice", icon:"🎤", name:"语音-末尾.mp3", desc:"（笑闹录音：汐泊诺思 + 铭泽。末尾，铭泽安静下来。）\n「……其实我有点怕。但万一她真的需要我呢。她一个小孩，在杭州，谁都不认识。\n  万一那些劝我的人是对的呢。可万一她说的都是真的呢。那我就得去。」", play:"点击播放语音（播放后显示上方转写）"},
      {t:"txt", icon:"📄", name:"留言.txt", desc:"「你忘了为啥去杭州就打开。别谢我，谢你自己还记得。—— 汐泊诺思」"}
    ],
    plan: { icon:"📄", name:"行程规划.txt", ev:4 },
    psych: { icon:"📄", name:"心理科就诊记录.txt" },
    encrypted: { name:"2026.07", icon:"🔒" },
    encPassword: "0725paofu",
    encFiles: [
      {t:"diary", icon:"🖼", name:"手写日记扫描件 ×5", desc:"（5 张扫描照片，字迹逐篇潦草——内容与「备忘录」中的日记一致。最后一张 7/24 深夜，最后一行字迹抖得几乎认不出。）", ev:8},
      {t:"morse", icon:"🔢", name:"摩斯电码对照表", desc:"一张折痕明显的手写对照表：字母 ↔ 摩斯符号。他为了听那段录音准备的。", ev:3, morseTable:true},
      {t:"folder", icon:"📁", name:"（空文件夹）如果我能出去", desc:"空的。"}
    ],
    imgGhost: { name:"IMG_0824_2353.jpg", icon:"📷", desc:"拍的是德州那个房间、桌上 Mac 屏幕亮着、时间 23:53、键盘上压着那张褪色的贴纸。\n拍摄时间：8月24日 23:53。\n8月24日。铭泽已经不在了。谁拍的？", src:"assets/room-dark.webp", ev:null }
  },
  trash: [
    {icon:"📷", name:"截图-杀猪盘特征.png", del:"7/25 00:01 删除", note:"7/24 深夜搜索「杀猪盘 特征」的结果页截图。他删了——不想让群友看到他在查。"},
    {icon:"📷", name:"帅气鲨团子-照片-缩略图.jpg", del:"7/25 00:03 删除", note:"缩略图未彻底清除，仅能看出是校服少女的轮廓。"},
    {icon:"📄", name:"她的资料.txt", del:"7/25 00:03 删除", ev:6, restoreText:"她说的信息整理：\n年龄：自称 17，实际 19（见面时确认）\n照片：她发来的是「初中照片」，文件 EXIF 显示拍摄于 2023 年\n「爸爸管得严」：她从未发过任何家庭照片\n地址：文三路 515 号，该地址不存在这户人家\n\n——人设是假的。她本人是真的（见「到时候再看」）。"}
  ],
  evidence: [
    {id:1, t:"她真实存在（「到时候再看」里的照片）"},
    {id:2, t:"摩斯求救信号 + 坐标（语音备忘录）"},
    {id:3, t:"摩斯电码对照表（加密文件夹）"},
    {id:4, t:"行程与地址（文三路 515 号）"},
    {id:5, t:"文三路 515 号楼外景照片"},
    {id:6, t:"她的资料（人设造假实锤）"},
    {id:7, t:"杭州反诈提醒新闻"},
    {id:8, t:"铭泽的手写日记（动机）"}
  ],
  endings: {
    bad: { title:"坏结局 · 别找我了", text:"凌晨 2 点 57 分。\n群里的头像亮了起来。\n我盯着屏幕，\n想起他说过——\n「如果看到我的号上线，别信。」\n\n可这条消息，我信了。\n\n「别找我了。」\n\n我没有点开它。\n也没有关掉电脑。\n屏幕的光照到天亮。\n头像暗下去的时候，\n和他说这话的时候一样快。\n\n后来我再也没见过那个头像亮起来。\n\n我不知道那是谁。\n也许是他自己。\n也许是别的什么。\n\n我只知道，\n我再也没等到他的报备。" },
    open: { title:"开放结局 · 快递已签收", text:"警方端了那个窝点的时候，\n里面已经没有人了。\n\n一个月后，\n我收到一条陌生号码的短信：\n「下次开黑，记得给我留个位子。」\n\n我回拨，已关机。\n我回了两个字：\n「收到。」\n\n那头再没有消息。\n\n我不知道那是他，\n还是别的什么。\n\n但我知道，\n他让我留个位子。\n\n位子我留了。\n留到现在。" },
    true: { title:"真结局 · 我回来了", text:"几个月后的一个晚上，\n群里突然多了一条语音。\n我点开。\n\n是铭泽的声音：\n「兄弟们，我回来了。……带回来一个人。」\n\n然后是她的声音，\n轻轻的：\n「AP 哥哥好。」\n\n我盯着屏幕，半天没说话。\n\n后来铭泽私聊我：\n「报备。我回来了。」\n\n我回他：\n「收到。」\n\n那天晚上我看了眼菜单栏，\n时间还停在 8 月 25 日 23:53。\n他在群里说：\n「别管它。它总这样。」\n\n我没问他为什么。\n有些信号，你无法证明来自活人，也无法证明不是。\n\n但这一次，\n我点开了那条语音。\n\n而他，\n真的回来了。" }
  },
  pseudo: {
    qqRecall: "（系统）8/25 00:00 铭哥 撤回了一条消息",
    voiceNote: { name:"留给AP.m4a", meta:"8/25 00:00 · 来自 iCloud 同步", src:"assets/morse.wav", note:"极轻的环境音。", decode:"解码：\n「文三路515 我等她」", ghost:"好像有极轻的呼吸声。你听了三遍，确定那是一个人握着手机，在等什么。" },
    file: { icon:"📄", name:"她的资料-补充.txt", desc:"（恢复后补全的内容）\n团伙称呼：水房。\n「聊手」轮班扮演同一个账号，话术剧本编号 S-17。\n她不是第一个。也不会是最后一个。\n铭泽知道了这件事，所以他没有走。" },
    ghostImgNote: "（窗户玻璃里，隐约有一个人影。你放大了看——看不清脸，但他站在那里。）"
  }
};